[package]
name = "fe_rtos"
version = "0.1.0"
authors = ["Bijan Tabatabai <bijan311@yahoo.com>"]
edition = "2018"

[dependencies]
fe_osi = { git = "https://github.com/badrobotics/fe_osi" }

[build-dependencies]
cc = "1.0.25"
