name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Switch to Nightly
      run: rustup default nightly && rustup update
    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install gcc-arm-none-eabi

    - name: Add Target M3
      run: rustup target add thumbv7m-none-eabi
    - name: Add Target M4, M7
      run: rustup target add thumbv7em-none-eabi
    - name: Add Target M4F
      run: rustup target add thumbv7em-none-eabihf
      
    - name: Build Cortex-M3
      run: cargo check --verbose --target=thumbv7m-none-eabi
    - name: Build Cortex-M4, M7
      run: cargo check --verbose --target=thumbv7em-none-eabi
    - name: Build Cortex-M4F, M7F
      run: cargo check --verbose --target=thumbv7em-none-eabihf

